### ISSUE TITLE
Rsync fails when using Bastion hosts

### ISSUE THREAD

**Issue by danielwrayois** [confluentinc/cp-ansible#104]
Hi,

The following parameter should be added to any synchronize (rysnc) commands:

```
use_ssh_args: yes
```

This will instruct Ansible to pass in any SSH arguments such as bastion hosts, connection attempt limits, and so on, to rysnc.

Without this flag I am seeing the following errors due to rsync trying to talk directly to a host in a private sub-net:
```
port 22: Connection timed out\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]\n", "rc": 255}
```

When I update the tasks, such as the one below, it works without issue:
```
- name: copy ssl related files to host
  synchronize:
    src: generated_ssl_files/
    dest: /var/ssl/private
    use_ssh_args: yes 
```
