### ISSUE TITLE
undocumented ansible_ssh_host required when using CA & Key Generation Strategy

### ISSUE THREAD

**Issue by SouquieresAdam** [confluentinc/cp-ansible#1162]
**Describe the issue**
Deploying a Cluster with the minimal configuration for tls/mutual_tls, the playbook fail 

with : 
ansible.errors.AnsibleUndefinedVariable: {{ [inventory_hostname, ansible_fqdn, ansible_host, ansible_ssh_host, hostname|default(omit)] | unique }}

during:
Create Openssl Config for SAN **Task**

**To Reproduce**
Configure inventory per https://docs.confluent.io/installer

+ ansible_host for each host to
+  ssl_enabled: true
 + ssl_mutual_auth_enabled: true
Run playbook

**Expected behaviour**
If ssl_custom_certs_remote_src is set to true, then any certificate validation should occur on the remote hosts. Delegating to localhost is not appropriate when this is the case.

**Inventory File**

```
all:
  vars:
    ansible_connection: ssh
    ansible_user: asouquieres
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/adam-gcp-nopwd
    ansible_ssh_common_args: -o StrictHostKeyChecking=no
    ssl_enabled: true
    ssl_mutual_auth_enabled: true

zookeeper:
  hosts:
    hostname1:
      ansible_host: 10.0.0.2
kafka_broker:
  hosts:
    hostname2:
      ansible_host: 10.0.0.3
    hostname3:
      ansible_host: 10.0.0.4
    hostname4:
      ansible_host: 10.0.0.5
schema_registry:
  hosts:
    hostname5:
      ansible_host: 10.0.0.6

ksql:
  hosts:
    hostname6:
      ansible_host: 10.0.0.7

kafka_connect:
  hosts:
    hostname7:
      ansible_host: 10.0.0.8

      vars:
        kafka_connect_confluent_hub_plugins:
          - confluentinc/kafka-connect-datagen:0.4.0

control_center:
  hosts:
    hostname8:
      ansible_host: 10.0.0.9
```
**Environment (please complete the following information):**

Source OS: MacOs Monterey
Target OS for all HOSTS : Vanilla Ubuntu 20.04 hosted on GCP
CP-Ansible Branch: ansible galaxy latest version
Ansible Version 2.12.3

**Workaround :**

Add ansible_ssh_host with same information as ansible_host for each host of the inventory
