### ISSUE TITLE
Add a var for ANSIBLE_MERGE_BEHAVIOUR=merge

### ISSUE THREAD

**Issue by timetravlr** [confluentinc/cp-ansible#1348]
We would like to have this be available as a variable to add to group_vars so it doesn't require doing this:
```
ANSIBLE_HASH_BEHAVIOUR=merge ansible-playbook -i inventories/site.yml confluent.platform.all --tags kafka_broker -l site-kafkatest-01 --skip-tags validate_hash_merge
```

cp-ansible/roles/common/tasks/main.yml requires this to be set in ansible.cfg or it fails.  
```
- name: Confirm Hash Merging Enabled
  assert:
    that: lookup('config', 'DEFAULT_HASH_BEHAVIOUR') == 'merge'
    fail_msg: "Hash Merging must be enabled in ansible.cfg"
  tags:
    - validate
    - validate_hash_merge
```

We use a central repo and we cannot have hash behaviour = merge set globally in ansible.cfg, or it will cause problems. It is difficult to only set this for one of our collections or repos. I know other issues have been reported on this in the past.
