### ISSUE TITLE
Omit create_mds_certs key creation for MDS

### ISSUE THREAD

**Issue by Slowdive-Aideron** [confluentinc/cp-ansible#1424]
**Describe the issue**
I'm trying to do a rolling redeployment of all my brokers. So i'm tearing down 1 VM at the time and executing cp-ansible (6.1.1-post) after each VM with the deployment_strategy=rolling . Problem is, all my MDS keys (public.pem and tokenKeypair.pem) are being re-created. This nukes my Control Center and it fails with "authenticatio failure" probably trying to establish a connection to the mds using different key / certs .. 

Even in a 100% functional installation , that has all the keys in place, i think this task is going to recreate the mds keys nevertheless : https://github.com/confluentinc/cp-ansible/blob/cce741def97ea8fff7432b800c70f643ee9bf291/tasks/certificate_authority.yml#L102 
and this one is going to copy / overwrite the existing ones : https://github.com/confluentinc/cp-ansible/blob/cce741def97ea8fff7432b800c70f643ee9bf291/roles/confluent.kafka_broker/tasks/rbac.yml#L48

Is there a way to safely omit the creation of the MDS keys ? while rbac_enabled: true ?

**To Reproduce**
Delete and re-create a broker VM. Execute cp-ansible, and see how MDS keys are re-created, CC loses access to the cluster

**Expected behaviour**
If the public.pem and tokenKeypair.pem is already there, it should not re-create and copy them to all the brokers, overwriting existing

**Inventory File**
unfortunatelly i cannot really provide that since it has sensitive information, but here are the important bits
```yaml
    # RBAC Configuration
    rbac_component_additional_system_admins:
    - topic_management
    rbac_enabled: true
    confluent_cli_download_enabled: false
    confluent_cli_path: "{{kafka_path}}/confluent-{{confluent_package_version}}/bin/confluent"
    ldap_truststore_location: "/some/path/ldap.jks"
    mds_super_user: srv_de-projectkaf-l-02
    mds_super_user_password: "{{projectkaf_l_02_password}}"
    control_center_ldap_user: srv_de-projectkaf-l-02
    control_center_ldap_password: "{{projectkaf_l_02_password}}"
    kafka_broker_ldap_user: srv_de-projectkaf-l-02
    kafka_broker_ldap_password: "{{projectkaf_l_02_password}}"

    # Kafka security Configuration
    ssl_enabled: true 
    ssl_mutual_auth_enabled: true # enable mtls
    zookeeper_ssl_enabled: false
    zookeeper_ssl_mutual_auth_enabled: false
```
If you need further config i can provide that

**Logs**
The ansible run itself does not fail . But attached is some of the stack traces from the CC 
[control-center.log.txt](https://github.com/confluentinc/cp-ansible/files/11770856/control-center.log.txt)

**Environment (please complete the following information):**
 - OS: RHEL 8.7
 - CP-Ansible Branch: [6.1.1-post]
 - Ansible Version [e.g. ansible core 2.12.7]

**Additional context**

**Comment by Slowdive-Aideron** [comment]
Hey, I've seen that in the newer cp-ansible versions you have regenerate_token_pem here https://github.com/confluentinc/cp-ansible/blob/7.4.0-post/playbooks/tasks/certificate_authority.yml#LL156C117-L156C137 

But as I understand it, if you don't have "controller_mds_private_key_stat" defined in the code or on the ansible controlle, the first when expression will be true anyway .. right ?! or am I misunderstanding something ? 

```yaml
  when: >
    (rbac_enabled|bool and create_mds_certs|bool and
    (not controller_mds_private_key_stat.stat.exists|bool or not controller_mds_public_key_stat.stat.exists|bool or regenerate_token_pem|bool))
``` 

Btw , the only services we are running are broker, zookeeper and CC.

**Comment by Slowdive-Aideron** [comment]
Hi, 

For any lost soul that is searching for a solution here : solution is to have all these three vars set 

```yaml
create_mds_certs: false # To provide your own MDS Certs set this variable and the next two
token_services_public_pem_file: /path/to/public.pem
token_services_private_pem_file: /path/to/tokenKeypair.pem
```

then this will resolve to false and the MDS certs are not renewed. 
```yaml
  when: >
    (rbac_enabled|bool and create_mds_certs|bool and
    (not controller_mds_private_key_stat.stat.exists|bool or not controller_mds_public_key_stat.stat.exists|bool or regenerate_token_pem|bool))
```
The MDS certs will still be deployed ! that happens in another part of the playbook. But the MDS Certs will stay the same 

This behaviour led to a production degradation on my project. If you exchange / reprovision a node and run cp-ansible in "rolling deployment" mode, ansible exchanges the MDS cert on all nodes but doesn't restart the confluent-server on the old / existing nodes .. Which means you will have a setup where one out of X broker will run with a completely different MDS cert. 

Plus your CC doesn't work anymore. This problem affects cp-ansible <= 7.1.1-post

Hope this helps anyone out there ..
