### ISSUE TITLE
[question] Unable to create SASL-SCRAM users in KRaft mode

### ISSUE THREAD

**Issue by Gianlu** [confluentinc/cp-ansible#1495]
Hello,
I'm using your collection in order to install Confluent Platform in KRaft mode and I tried to create SASL-SCRAM user but the playbook fail and, looking at your code, user cration is only upported in Zookeeper mode.
Have you plan to support user creatin in KRaft mode? If yes, when?
We are testing Confluent and I have to plan a rollout but I woluld like to deploy in Kraft mode.

**Inventory File**
```YAML
all:
  hosts:
    localhost:
      ansible_become: false
      ansible_connection: local
  vars:
    ssl_enabled: true
    ssl_custom_certs: true
    ssl_ca_cert_filepath: "/tmp/ca-chain.cert.pem"
    ssl_signed_cert_filepath: '/tmp/cert.pem'
    ssl_key_filepath: '/tmp/cert.key'
    debian_java_package_name: openjdk-11-jdk
    confluent_server_enabled: false 
    telemetry_enabled: false
    sasl_protocol: scram
    mask_secrets: true
    sasl_scram_users:
      user1:
        principal: user1
        password: my-secret
  children:
    kafka_contoller:
      hosts:
        server01.domain.lcl:
          ansible_host: 192.168.0.201
        server03.domain.lcl:
          ansible_host: 192.168.0.199
        server03.domain.lcl:
          ansible_host: 192.168.0.200
    kafka_broker:
      vars:
        kafka_broker_custom_properties:
          log.dirs: /opt/data/kafka/data
      hosts:
        server01.domain.lcl:
        server01.domain.lcl:
        server01.domain.lcl:
```

**Environment:**
 - OS: Debian 10.13
 - CP-Ansible Branch: 7.5.1
 - Ansible Version: ansible [core 2.15.3]
