### ISSUE TITLE
Add More Override Documentation

### ISSUE THREAD

**Issue by prestonmcgowan** [confluentinc/cp-ansible#212]
Add Zookeeper Data Directory override
```
all:
  vars:
     zookeeper:
         properties:
              dataDir: {your path}
```

Add Connect Cluster advice
```
Don't forget to configure c3 for additional connect clusters
```
