### ISSUE TITLE
Document usage of different ip/hostname for listener

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#325]
When setting up a listener one can change the ip/hostanme for that.
The code of this roles is able to do so, however one could add that to the example hosts file.

I can create a PR if this is a desirable addition :)
e.g.

```
       broker:
         name: BROKER
         port: 9091
         ssl_enabled: false
         ssl_mutual_auth_enabled: false
         sasl_protocol: none
       internal:
         name: INTERNAL
         port: 9092
		 hostname: ip-172-31-18-160.us-west-2.compute.internal:19091
         ssl_enabled: true
         ssl_mutual_auth_enabled: false
         sasl_protocol: scram

**Comment by domenicbove** [comment]
ya... this features is super helpful when working with aws, what i usually do is this:

```
kafka_broker:
  vars:
    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093
  hosts:
    ip-172-31-43-14.us-west-2.compute.internal:
      ansible_ssh_host: ec2-34-209-19-19.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-209-19-19.us-west-2.compute.amazonaws.com
```
