### ISSUE TITLE
Permission rights on log folders

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#378]
Currently we set `764` as rights for the log folders.

eg 

```
- name: Create Logs Directory
  file:
    path: "{{kafka_broker.appender_log_path}}"
    state: directory
    group: "{{kafka_broker_group}}"
    owner: "{{kafka_broker_user}}"
    mode: '764'
```

imho 750 or 755 makes more sense, since you need the execution bit to actually read the files inside.

For data dir we actually do set 0750

```
- name: Set Permissions on Data Dirs
  file:
    path: "{{item}}"
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    state: directory
    mode: 0750
  with_items: "{{kafka_broker.datadir}}"
```

Stumbled upon this at a customer where we added splunk to the kafka-group to export the logs and need to change the log dir props accordingly.

Generally`0755` might be the better choice, if you do not want to touch the "technical user groups" for kafka
