### ISSUE TITLE
Add a restart methodology

### ISSUE THREAD

**Issue by cotedm** [confluentinc/cp-ansible#39]
We should have a way to restart the services via a play. This is potentially quite complex because rolling restarting Kafka brokers and ZooKeeper servers is non-trivial.

**Comment by cricket007** [comment]
Sample playbook we have for rolling restarts

```yaml
- hosts: broker
  serial: 1
  become: yes

  tasks:
    - lineinfile:
        state: absent
        dest: /etc/systemd/system/confluent-kafka.service
        regexp: '^Restart=always'

    - lineinfile:
        state: present
        dest: /etc/systemd/system/confluent-kafka.service
        regexp: '^TimeoutStopSec'
        insertafter: '^LimitNOFILE'
        line: 'TimeoutStopSec=600'

    - systemd: name=confluent-kafka daemon_reload=yes state=restarted

    - wait_for:
        host: '{{ ansible_default_ipv4.address }}'
        port: "{{ kafka.broker.port }}"
        timeout: 1800
        sleep: 60
        delay: 30
        state: present
```
