### ISSUE TITLE
Synchronize module partially broken

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#390]
Sadly the tasks that include copying data back from a host to the Ansible Controller via `synchronize` module can be broken. The error message says something like:
```
 no tty present and no askpass program specified
```

Especially that behavior seems to occur, if remote servers do NOT have passwd-less entries for rsync.

A fix that I found to work (so far) is simply to amend the module call with the `rsync_path` flag like

```
- name: Copy Generated SSL Files Back to Ansible Host
  synchronize:
    src: /var/ssl/private/generation/out/
    dest: "generated_ssl_files"
    mode: pull
    rsync_path: /bin/rsync
```

The source of the workaround is to be found here:
https://github.com/ansible/ansible/issues/20769#issuecomment-546438205

I am aware that `confluent.common` already contains a task to anticipate problems with `synchronize`

```
- name: Disable Require TTY in Sudoers (required for ansible synchronize)
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: '^Defaults\s+requiretty.*$'
```

However I do have customers that do central Server-Basis Management with Puppet including their sudoers file. Meaning after 30 min the task is sadly obsolete :P

Did anybody every experience similar issues?
