### ISSUE TITLE
Unable to override a single config key

### ISSUE THREAD

**Issue by cricket007** [confluentinc/cp-ansible#45]
In the process of making a Vagrantfile, and while I was starting up a single broker, I wanted to limit the log retention and decrease the replicator factors, so I tried this

```ruby
brokers = ["cp-kafka"]
replication_factor = [3, brokers.length].min
ansible.groups = {
  "all:vars" => {"security_mode" => "plaintext"},
  "zookeeper" => ["cp-zk"],
  "broker" => ["cp-kafka"],
  "broker:vars" => {"kafka" => "{'broker': {'config': {"\
    "'log.retention.hours': 48,"\
    "'offsets.topic.replication.factor': #{replication_factor},"\
    "'transaction.state.log.replication.factor': #{replication_factor}"\
    "}}"
},
```

However, upon running, I got the error that stopped at the user-group creation because `kafka.broker` was now overridden with only having a `config` dictionary. It doesn't have the `kafka.broker.group` anymore. 

I have a workaround that is this, but wanted to know if there was an alternative before patching. 

Prefix with `kafka_` and replace `.` with `_`

```ruby
"broker:vars" => {
    "kafka_log_retention_hours" => 48
    ...
```

Update the `defaults.yml`

```yaml
kafka_log_retention_hours: 168
kafka_offsets_topic_replication_factor: 3
kafka_transaction_state_log_replication_factor: 3

kafka:
  broker:
    ...
    config:
      ...
      log.retention.hours: "{{kafka_log_retention_hours}}"
      ...
```

Same error might happen if setting any single property under `kafka => broker` because it seems the group variables aren't merged
