### ISSUE TITLE
Upgrade playbooks in from 5.5.1 to 6.0.0

### ISSUE THREAD

**Issue by nbchn** [confluentinc/cp-ansible#495]
**Describe the issue**
Following the [upgrade documentation](https://docs.confluent.io/ansible/current/ansible-upgrade.html), we made an upgrade of the whole platform from 5.5.1 to 6.0.0 and we faced a few minor issues that might be good to fix:
- upgrade_zookeeper.yml and upgrade_kafka_broker.yml failed because it tried to backup respectively `server.properties` and `zookeeper.properties`, even though I understand that it is useful when the colocating of broker and zookeeper, I think that it should not make the playbook fail.
[upgrade_kafka_broker.yml l.144](https://github.com/confluentinc/cp-ansible/blob/6.0.0-post/upgrade_kafka_broker.yml#L144)
[upgrade_kafka_broker.yml l.204](https://github.com/confluentinc/cp-ansible/blob/6.0.0-post/upgrade_kafka_broker.yml#L204)
[upgrade_zookeeper.yml l.122](https://github.com/confluentinc/cp-ansible/blob/6.0.0-post/upgrade_zookeeper.yml#L122)
[upgrade_zookeeper.yml l.189](https://github.com/confluentinc/cp-ansible/blob/6.0.0-post/upgrade_zookeeper.yml#L189)
- We were using a custom repository so it might have an impact but we had to add `update_cache: yes` on all yum install module tasks (it's done systematically for debian).
- There is a typo on [upgrade_ksql.yml l.131](https://github.com/confluentinc/cp-ansible/blob/6.0.0-post/upgrade_ksql.yml#L131)

**To Reproduce**
1. Install the platform using cp-ansible 5.5.1
2. Follow the [upgrade guide](https://docs.confluent.io/ansible/current/ansible-upgrade.html)

**Environment (please complete the following information):**
 - OS: RHEL 7.5
 - CP-Ansible Branch: 6.0.0-post

**Comment by JumaX** [comment]
@nbchn Thanks for the report.  I will investigate this today and see about getting a fix in for the spelling mistake.  

Regarding the missing server.properties, I suspect this is due to the custom repo.  Generally when you install our packages, there should always be a server.properties, even if it just contains default values, so the fact it wasn't present is suspicious.

Also note, we are currently re-evaluating our upgrade playbooks and plan writing them in the new year.

**Comment by domenicbove** [comment]
Hi @nbchn thanks for the feedback! I just fixed the typo in the upgrade_ksql.yml playbook. 

For the other 2 points:

- How did backing up those files cause a failure. You are right- backing up both server.properties and zookeeper.properties is redundant on a non colocated host, but it really should not cause a failure because both files should exist even if only one file is getting used (they are shipped with the packages)

- You are suggesting we make this change here: https://github.com/confluentinc/cp-ansible/blob/6.0.1-post/upgrade_kafka_broker.yml#L179

```
    - name: Install the Packages - Red Hat
      yum:
        name: "{{item}}{{confluent_package_redhat_suffix}}"
        state: latest
        update_cache: true
      loop: "{{ kafka_broker_packages }}"
      when: ansible_os_family == "RedHat"
      # Packages will not be found in check mode because repos not changed
      ignore_errors: "{{ ansible_check_mode }}"
```

That seems fine to be honestly since we are setting the same flag for debian
