### ISSUE TITLE
Missing auth in REST call against Jolokia

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#498]
We are using Basic Auth for Jolokia and there might be a missing auth parameter block in the task file for creating ordered kafka groups:

At least we had to do the following changes in order to get it running:

```
- name: Get ActiveControllerCount
  uri:
    url: "{{ kafka_broker_jolokia_active_controller_url }}"
    validate_certs: false
++  force_basic_auth: true
++  url_username: "{{kafka_broker_jolokia_user}}"
++  url_password: "{{kafka_broker_jolokia_password}}"
    return_content: true
    status_code: 200
  register: active_controller_count
```

**Environment
 - OS: RHEL 7.6
 - CP-Ansible Branch: 5.5.x-post
 - Ansible Version ansible 2.9.6
