### ISSUE TITLE
Add Connectors using confluent-hub

### ISSUE THREAD

**Issue by cricket007** [confluentinc/cp-ansible#51]
Add a module to run `confluent-hub-install {{ item }}` with a list of Confluent Hub items. 

```yaml
kafka:
  connect:
    distributed:
      confluent_hub_packages:
        - debezium/debezium-connector-mysql:latest
```

https://docs.ansible.com/ansible/2.6/dev_guide/developing_modules_general.html
