### ISSUE TITLE
Listeners - multiple network interfaces support

### ISSUE THREAD

**Issue by nbisson** [confluentinc/cp-ansible#513]
Hi all,

I would like to know if it's possible to implement in cp-ansible the multiple network interfaces support.

Like this [doc said ](https://www.confluent.fr/blog/kafka-listeners-explained/), we can make listeners who listen only one network interface.

```
KAFKA_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092
KAFKA_ADVERTISED_LISTENERS: LISTENER_BOB://kafka0:29092,LISTENER_FRED://localhost:9092
```

However, today, cp-ansible implements this code :
```
listeners: "{% for listener in kafka_broker_listeners|dict2items %}{% if loop.index > 1%},{% endif %}{{ listener['value']['name'] }}://:{{ listener['value']['port'] }}{% endfor %}"
advertised.listeners: "{% for listener in kafka_broker_listeners|dict2items %}{% if loop.index > 1%},{% endif %}{{ listener['value']['name'] }}://{{ listener['value']['hostname'] | default(inventory_hostname) }}:{{ listener['value']['port'] }}{% endfor %}"
```

We can see that all listeners listen on same network interface.

It will be nice to have :
```
    #### Configuring Multiple Listeners ####
    ## CP-Ansible will configure two listeners on the broker: a broker listener for the broker to communicate and an internal for the components and other clients.
    ## If you only need one listener uncomment this line:
    # kafka_broker_configure_multiple_listeners: false
    ## By default both of these listeners will follow whatever you set for ssl_enabled and sasl_protocol.
    ## To configure different security settings on the internal and external listeners set the following variables:
    kafka_broker_custom_listeners:
      broker:
        name: LISTENER_FRED
        network: localhost
        port: 9092
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none
      internal:
        name: LISTENER_BOB
        network: kafka0
        port: 29092
        ssl_enabled: true
        ssl_mutual_auth_enabled: false
        sasl_protocol: scram
```

Thank you in advance.

**Comment by domenicbove** [comment]
So far we have had success with allowing for customization of _just the advertised listener hostname_: https://docs.confluent.io/ansible/current/ansible-configure.html#add-advertised-listener-hostnames

And we are using the `hostname` key as what to put into the advertised listener. 

Per the doc you shared, this is the set up most people need:
```
listeners=INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
advertised.listeners=INTERNAL://ip-172-31-18-160.us-west-2.compute.internal:19092,EXTERNAL://ec2-54-191-84-122.us-west-2.compute.amazonaws.com:9092
inter.broker.listener.name=INTERNAL
```

Can you let me know what your network architecture looks like, because if you are simply on AWS maybe you can just use the hostname field. 

Additionally, and this is a little hacky, all properties are customizable. So you could have something like this in your inventory:

```
all:
  vars:
    kafka_broker_custom_listeners:
      client_listener:
        name: CLIENT
        port: 9093

kafka_broker:
  hosts:
    ip-172-31-43-14.us-west-2.compute.internal:
      kafka_broker_custom_properties:
        listeners: BROKER://0.0.0.0:9091,INTERNAL://localhost:9092,CLIENT://ip-172-31-43-14.us-west-2.compute.internal:9093
      kafka_broker_custom_listeners:
        client_listener:
          hostname: ec2-34-209-19-18.us-west-2.compute.amazonaws.com
    ip-172-31-43-15.us-west-2.compute.internal:
      kafka_broker_custom_properties:
        listeners: BROKER://0.0.0.0:9091,INTERNAL://localhost:9092,CLIENT://ip-172-31-43-15.us-west-2.compute.internal:9093
      kafka_broker_custom_listeners:
        client_listener:
          hostname: ec2-34-209-19-19.us-west-2.compute.amazonaws.com
```
