### ISSUE TITLE
Serial ordered runs with sasl_protocol: plain create malformed super.users

### ISSUE THREAD

**Issue by jkmart** [confluentinc/cp-ansible#569]
**Describe the issue**
When running the playbook a second time after an initial provisioning, it runs in serial order for kafka_broker. During these runs, the server.properties file will occasionally get malformed entries like `super.users=User:dom;User:jeff;User:mds;admin;User:admin;User:User:admin`

When there is an unnormalized name like "admin" instead of "User:admin", there is an unhandled exception and the broker will fail to start. Malformed entries like "User:User:admin" will not affect startup.

**To Reproduce**
Set `sasl_protocol: plain` in the inventory, and any other related settings to make that work.

**Expected behaviour**
The super.users in the server.properties file should contain only well-formed entries like `super.users=User:dom;User:jeff;User:mds;User:admin`

**Logs**
```
2021-03-02 10:53:55,754 p=112393 u=kmartin n=ansible | TASK [confluent.kafka_broker : Add Super Users list to Kafka Properties] ***********************************************************************************************************************************************************
2021-03-02 10:53:55,754 p=112393 u=kmartin n=ansible | Tuesday 02 March 2021  10:53:55 -0500 (0:00:00.049)       0:00:59.584 ********* 
2021-03-02 10:53:56,154 p=112393 u=kmartin n=ansible | ok: [ip-172-31-40-8.ec2.internal] => {
    "ansible_facts": {
        "kafka_broker_final_properties": {
            "advertised.listeners": "INTERNAL://ip-172-31-40-8.ec2.internal:9092,BROKER://ip-172-31-40-8.ec2.internal:9091,CLIENT://ip-172-31-40-8.ec2.internal:9093",
            "authorizer.class.name": "io.confluent.kafka.security.authorizer.ConfluentServerAuthorizer",
            "broker.id": "1",
            "confluent.ansible.managed": "true",
            "confluent.authorizer.access.rule.providers": "CONFLUENT,ZK_ACL",
            "confluent.balancer.topic.replication.factor": "3",
            "confluent.license.topic": "_confluent-license",
            "confluent.license.topic.replication.factor": "3",
            "confluent.metadata.server.advertised.listeners": "https://ip-172-31-40-8.ec2.internal:8090",
            "confluent.metadata.server.authentication.method": "BEARER",
            "confluent.metadata.server.listeners": "https://0.0.0.0:8090",
            "confluent.metadata.server.public.key.path": "/var/ssl/private/public.pem",
            "confluent.metadata.server.ssl.key.password": "confluentkeystorestorepass",
            "confluent.metadata.server.ssl.keystore.location": "/var/ssl/private/kafka_broker.keystore.jks",
            "confluent.metadata.server.ssl.keystore.password": "confluentkeystorestorepass",
            "confluent.metadata.server.ssl.truststore.location": "/var/ssl/private/kafka_broker.truststore.jks",
            "confluent.metadata.server.ssl.truststore.password": "confluenttruststorepass",
            "confluent.metadata.server.token.auth.enable": "true",
            "confluent.metadata.server.token.key.path": "/var/ssl/private/tokenKeypair.pem",
            "confluent.metadata.server.token.max.lifetime.ms": 3600000,
            "confluent.metadata.server.token.signature.algorithm": "RS256",
            "confluent.metadata.topic.replication.factor": "3",
            "confluent.metrics.reporter.bootstrap.servers": "ip-172-31-45-20.ec2.internal:9091,ip-172-31-40-8.ec2.internal:9091,ip-172-31-37-156.ec2.internal:9091",
            "confluent.metrics.reporter.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"admin-secret\";",
            "confluent.metrics.reporter.sasl.mechanism": "PLAIN",
            "confluent.metrics.reporter.security.protocol": "SASL_SSL",
            "confluent.metrics.reporter.ssl.key.password": "confluentkeystorestorepass",
            "confluent.metrics.reporter.ssl.keystore.location": "/var/ssl/private/kafka_broker.keystore.jks",
            "confluent.metrics.reporter.ssl.keystore.password": "confluentkeystorestorepass",
            "confluent.metrics.reporter.ssl.truststore.location": "/var/ssl/private/kafka_broker.truststore.jks",
            "confluent.metrics.reporter.ssl.truststore.password": "confluenttruststorepass",
            "confluent.metrics.reporter.topic.replicas": "3",
            "confluent.schema.registry.url": "https://ip-172-31-89-93.ec2.internal:8081",
            "confluent.security.event.logger.exporter.kafka.topic.replicas": "3",
            "confluent.ssl.key.password": "confluentkeystorestorepass",
            "confluent.ssl.keystore.location": "/var/ssl/private/kafka_broker.keystore.jks",
            "confluent.ssl.keystore.password": "confluentkeystorestorepass",
            "confluent.ssl.truststore.location": "/var/ssl/private/kafka_broker.truststore.jks",
            "confluent.ssl.truststore.password": "confluenttruststorepass",
            "confluent.support.customer.id": "anonymous",
            "confluent.support.metrics.enable": "true",
            "group.initial.rebalance.delay.ms": 3000,
            "inter.broker.listener.name": "BROKER",
            "kafka.rest.bootstrap.servers": "ip-172-31-45-20.ec2.internal:9092,ip-172-31-40-8.ec2.internal:9092,ip-172-31-37-156.ec2.internal:9092",
            "kafka.rest.client.security.protocol": "SASL_SSL",
            "kafka.rest.client.ssl.key.password": "confluentkeystorestorepass",
            "kafka.rest.client.ssl.keystore.location": "/var/ssl/private/kafka_broker.keystore.jks",
            "kafka.rest.client.ssl.keystore.password": "confluentkeystorestorepass",
            "kafka.rest.client.ssl.truststore.location": "/var/ssl/private/kafka_broker.truststore.jks",
            "kafka.rest.client.ssl.truststore.password": "confluenttruststorepass",
            "kafka.rest.confluent.metadata.basic.auth.user.info": "mds:password",
            "kafka.rest.confluent.metadata.bootstrap.server.urls": "https://ip-172-31-45-20.ec2.internal:8090,https://ip-172-31-40-8.ec2.internal:8090,https://ip-172-31-37-156.ec2.internal:8090",
            "kafka.rest.confluent.metadata.http.auth.credentials.provider": "BASIC",
            "kafka.rest.confluent.metadata.ssl.truststore.location": "/var/ssl/private/kafka_broker.truststore.jks",
            "kafka.rest.confluent.metadata.ssl.truststore.password": "confluenttruststorepass",
            "kafka.rest.enable": "true",
            "kafka.rest.kafka.rest.resource.extension.class": "io.confluent.kafkarest.security.KafkaRestSecurityResourceExtension",
            "kafka.rest.public.key.path": "/var/ssl/private/public.pem",
            "kafka.rest.rest.servlet.initializor.classes": "io.confluent.common.security.jetty.initializer.InstallBearerOrBasicSecurityHandler",
            "ldap.com.sun.jndi.ldap.read.timeout": 3000,
            "ldap.group.member.attribute.pattern": "CN=(.*),OU=rbac,DC=example,DC=com",
            "ldap.group.name.attribute": "cn",
            "ldap.group.search.base": "OU=rbac,DC=example,DC=com",
            "ldap.java.naming.factory.initial": "com.sun.jndi.ldap.LdapCtxFactory",
            "ldap.java.naming.provider.url": "ldap://ip-172-31-88-191.ec2.internal:389",
            "ldap.java.naming.security.authentication": "simple",
            "ldap.java.naming.security.credentials": "password",
            "ldap.java.naming.security.principal": "uid=mds,OU=rbac,DC=example,DC=com",
            "ldap.user.memberof.attribute.pattern": "CN=(.*),OU=rbac,DC=example,DC=com",
            "ldap.user.name.attribute": "uid",
            "ldap.user.object.class": "account",
            "ldap.user.search.base": "OU=rbac,DC=example,DC=com",
            "listener.name.broker.plain.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"admin-secret\"  user_admin=\"admin-secret\" user_client=\"client-secret\" user_kafka_connect=\"kafka_connect-secret\" user_control_center=\"control_center-secret\" user_kafka_rest=\"kafka_rest-secret\" user_ksql=\"ksql-secret\" user_schema_registry=\"schema_registry-secret\" user_kafka_connect_replicator=\"kafka_connect_replicator-secret\";",
            "listener.name.broker.sasl.enabled.mechanisms": "PLAIN",
            "listener.name.broker.ssl.client.auth": "required",
            "listener.name.broker.ssl.key.password": "confluentkeystorestorepass",
            "listener.name.broker.ssl.keystore.location": "/var/ssl/private/kafka_broker.keystore.jks",
            "listener.name.broker.ssl.keystore.password": "confluentkeystorestorepass",
            "listener.name.broker.ssl.truststore.location": "/var/ssl/private/kafka_broker.truststore.jks",
            "listener.name.broker.ssl.truststore.password": "confluenttruststorepass",
            "listener.name.client.plain.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"admin-secret\"  user_admin=\"admin-secret\" user_client=\"client-secret\" user_kafka_connect=\"kafka_connect-secret\" user_control_center=\"control_center-secret\" user_kafka_rest=\"kafka_rest-secret\" user_ksql=\"ksql-secret\" user_schema_registry=\"schema_registry-secret\" user_kafka_connect_replicator=\"kafka_connect_replicator-secret\";",
            "listener.name.client.sasl.enabled.mechanisms": "PLAIN",
            "listener.name.client.ssl.client.auth": "required",
            "listener.name.client.ssl.key.password": "confluentkeystorestorepass",
            "listener.name.client.ssl.keystore.location": "/var/ssl/private/kafka_broker.keystore.jks",
            "listener.name.client.ssl.keystore.password": "confluentkeystorestorepass",
            "listener.name.client.ssl.truststore.location": "/var/ssl/private/kafka_broker.truststore.jks",
            "listener.name.client.ssl.truststore.password": "confluenttruststorepass",
            "listener.name.internal.oauthbearer.sasl.jaas.config": "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required publicKeyPath=\"/var/ssl/private/public.pem\";",
            "listener.name.internal.oauthbearer.sasl.login.callback.handler.class": "io.confluent.kafka.server.plugins.auth.token.TokenBearerServerLoginCallbackHandler",
            "listener.name.internal.oauthbearer.sasl.server.callback.handler.class": "io.confluent.kafka.server.plugins.auth.token.TokenBearerValidatorCallbackHandler",
            "listener.name.internal.sasl.enabled.mechanisms": "OAUTHBEARER",
            "listener.name.internal.ssl.client.auth": "required",
            "listener.name.internal.ssl.key.password": "confluentkeystorestorepass",
            "listener.name.internal.ssl.keystore.location": "/var/ssl/private/kafka_broker.keystore.jks",
            "listener.name.internal.ssl.keystore.password": "confluentkeystorestorepass",
            "listener.name.internal.ssl.truststore.location": "/var/ssl/private/kafka_broker.truststore.jks",
            "listener.name.internal.ssl.truststore.password": "confluenttruststorepass",
            "listener.security.protocol.map": "INTERNAL:SASL_SSL,BROKER:SASL_SSL,CLIENT:SASL_SSL",
            "listeners": "INTERNAL://:9092,BROKER://:9091,CLIENT://:9093",
            "log.dirs": "/var/lib/kafka/data",
            "log.retention.check.interval.ms": 300000,
            "log.retention.hours": 168,
            "log.segment.bytes": 1073741824,
            "metric.reporters": "io.confluent.metrics.reporter.ConfluentMetricsReporter",
            "num.io.threads": 16,
            "num.network.threads": 8,
            "num.partitions": 1,
            "num.recovery.threads.per.data.dir": 2,
            "offsets.topic.replication.factor": "3",
            "sasl.enabled.mechanisms": "OAUTHBEARER,PLAIN",
            "sasl.mechanism.inter.broker.protocol": "PLAIN",
            "socket.receive.buffer.bytes": 102400,
            "socket.request.max.bytes": 104857600,
            "socket.send.buffer.bytes": 102400,
            "super.users": "User:dom;User:jeff;User:mds;User:admin",
            "transaction.state.log.min.isr": "2",
            "transaction.state.log.replication.factor": "3",
            "zookeeper.clientCnxnSocket": "org.apache.zookeeper.ClientCnxnSocketNetty",
            "zookeeper.connect": "ip-172-31-45-20.ec2.internal:2182,ip-172-31-40-8.ec2.internal:2182,ip-172-31-37-156.ec2.internal:2182",
            "zookeeper.connection.timeout.ms": 18000,
            "zookeeper.ssl.client.enable": "true",
            "zookeeper.ssl.keystore.location": "/var/ssl/private/kafka_broker.keystore.jks",
            "zookeeper.ssl.keystore.password": "confluentkeystorestorepass",
            "zookeeper.ssl.truststore.location": "/var/ssl/private/kafka_broker.truststore.jks",
            "zookeeper.ssl.truststore.password": "confluenttruststorepass"
        }
    },
    "changed": false
}
```

**Environment (please complete the following information):**
 - OS: RHEL 7.9
 - CP-Ansible Branch: 6.1.0-post
 - Ansible Version ansible 2.10.4, and also found with 2.9.16

**Additional context**
The result of super.users is non-deterministic and seems to do with lazy loading on the Ansible side due to the user of "{{ variable_name}}" in conjunction with `delegate_to`.

**Inventory File**
```
all:
  vars:
    ansible_connection: ssh
    ansible_user: ec2-user
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_private_key_file: /home/kmartin/.ssh/confluent-base.pem
    installation_method: package

    jolokia_enabled: true
    jolokia_url_remote: false
    jolokia_jar_url: jolokia-jvm-1.6.2-agent.jar
    jmxexporter_enabled: true
    jmxexporter_url_remote: false
    jmxexporter_jar_url: jmx_prometheus_javaagent-0.12.0.jar

    ssl_enabled: true
    ssl_mutual_auth_enabled: true

    sasl_protocol: plain

    rbac_enabled: true

    kafka_broker_custom_listeners:
      client_listener:
        name: CLIENT
        port: 9093

    mds_super_user: mds
    mds_super_user_password: password

    schema_registry_ldap_user: schema-registry1
    schema_registry_ldap_password: password

    kafka_connect_ldap_user: kafka-connect1
    kafka_connect_ldap_password: password

    ksql_ldap_user: ksql1
    ksql_ldap_password: password

    kafka_rest_ldap_user: kafka-rest1
    kafka_rest_ldap_password: password

    control_center_ldap_user: control-center1
    control_center_ldap_password: password

    kafka_broker_custom_properties:
      super.users: User:dom;User:jeff
    confluent_cli_download_enabled: false

zookeeper:
  hosts:
    ip-172-31-38-148.ec2.internal:
      ansible_port: 22
      ansible_host: ec2-54-235-13-236.compute-1.amazonaws.com
      zookeeper_id: 0
    ip-172-31-36-29.ec2.internal:
      ansible_port: 22
      ansible_host: ec2-54-175-17-229.compute-1.amazonaws.com
      zookeeper_id: 1
    ip-172-31-32-60.ec2.internal:
      ansible_port: 22
      ansible_host: ec2-18-234-96-112.compute-1.amazonaws.com
      zookeeper_id: 2

kafka_broker:
  vars:
    kafka_broker_custom_properties:
      ldap.java.naming.factory.initial: com.sun.jndi.ldap.LdapCtxFactory
      ldap.com.sun.jndi.ldap.read.timeout: 3000
      ldap.java.naming.provider.url: ldap://{{ groups['ldap_server'][0] }}:389
      ldap.java.naming.security.principal: uid=mds,OU=rbac,DC=example,DC=com
      ldap.java.naming.security.credentials: password
      ldap.java.naming.security.authentication: simple
      ldap.user.search.base: OU=rbac,DC=example,DC=com
      ldap.group.search.base: OU=rbac,DC=example,DC=com
      ldap.user.name.attribute: uid
      ldap.user.memberof.attribute.pattern: CN=(.*),OU=rbac,DC=example,DC=com
      ldap.group.name.attribute: cn
      ldap.group.member.attribute.pattern: CN=(.*),OU=rbac,DC=example,DC=com
      ldap.user.object.class: account
  hosts:
    ip-172-31-38-148.ec2.internal:
      ansible_port: 22
      ansible_host: ec2-54-235-13-236.compute-1.amazonaws.com
      broker_id: 0
    ip-172-31-36-29.ec2.internal:
      ansible_port: 22
      ansible_host: ec2-54-175-17-229.compute-1.amazonaws.com
      broker_id: 1
    ip-172-31-32-60.ec2.internal:
      ansible_port: 22
      ansible_host: ec2-18-234-96-112.compute-1.amazonaws.com
      broker_id: 2

# provision test ldap server
ldap_server:
  vars:
    ldaps_enabled: false
    ldaps_custom_certs: false

    ldap_admin_password: ldppassword

    ldap_rbac_group: rbac
    ldap_dc: example
    ldap_dc_extension: com

    ldap_users:
      - username: "{{schema_registry_ldap_user}}"
        password: "{{schema_registry_ldap_password}}"
        uid: 9998
        guid: 98
      - username: "{{kafka_connect_ldap_user}}"
        password: "{{kafka_connect_ldap_password}}"
        uid: 9997
        guid: 97
      - username: "{{ksql_ldap_user}}"
        password: "{{ksql_ldap_password}}"
        uid: 9996
        guid: 96
      - username: "{{control_center_ldap_user}}"
        password: "{{control_center_ldap_password}}"
        uid: 9995
        guid: 95
      - username: "{{kafka_rest_ldap_user}}"
        password: "{{kafka_rest_ldap_password}}"
        uid: 9994
        guid: 94
      - username: "{{mds_super_user}}"
        password: "{{mds_super_user_password}}"
        uid: 9993
        guid: 93
  hosts:
    ip-172-31-89-195.ec2.internal:
      ansible_port: 22
      ansible_host: ec2-3-86-109-93.compute-1.amazonaws.com
```
