### ISSUE TITLE
Feature request: MaxBackupIndex/MaxFileSize should be configurable in update_log4j.yml

### ISSUE THREAD

**Issue by erikgb** [confluentinc/cp-ansible#589]
We would like to modify the currently hard-coded values for MaxBackupIndex/MaxFileSize in `update_log4j.yml`, and on the `6.1.0-post` branch, our only option seems to be to provide our own (full) custom log4j-configuration. It would be nice if the hard-coded values 10/100MB were changed to default value that could be set in our inventory!

On the `6.0.2-post` branch, it was possible to achieve what we want - using "private" variables (not mentioned in VARIABLES.md):
```yaml
kafka_broker:
  kafka_appender_max_log_files: 7
  state_change_appender_max_log_files: 7
  request_appender_max_log_files: 7
  cleaner_appender_max_log_files: 7
  controller_appender_max_log_files: 7
  authorizer_appender_max_log_files: 7
  metadata_appender_max_log_files: 7
```
