### ISSUE TITLE
C3 log dir permissions task unnecessary

### ISSUE THREAD

**Issue by domenicbove** [confluentinc/cp-ansible#633]
**Describe the issue**
This task:
```
- name: Set Permissions on /var/log/confluent
  file:
    path: /var/log/confluent/
    owner: "{{control_center_user}}"
    group: "{{control_center_group}}"
    mode: 0770
    state: directory
```

Should not be necessary with the inclusion of:
```
control_center_service_environment_overrides:
  CONTROL_CENTER_LOG4J_OPTS: "{% if control_center_custom_log4j|bool %}-Dlog4j.configuration=file:{{control_center.log4j_file}}{% endif %}"
  LOG_DIR: "{{ control_center_log_dir|regex_replace('\\/$', '') }}"
```

Test its removal against both archive and package install, consider colocated instance as well
