### ISSUE TITLE
FIPS Listener without full FIPS enablement

### ISSUE THREAD

**Issue by prestonmcgowan** [confluentinc/cp-ansible#646]
**Describe the issue**
Several installations would like to make use of the FIPS ciphers for Listeners. The current implementation of setting `fips_enabled` sets the kafka property for FIPS and sets up the Kafka Listeners to use the Bouncy Castle ciphers.
If the installation calls for a listener that is not encrypted, the `fips_enabled` stops Kafka from executing. Once the user then removes the `fips_enabled` all of the Bouncy Castle logic is disabled. Therefore, I would like an intermediate capability.

I would like to have a single listener that is FIPS, while the others are SASL or PLAINTEXT.

**Sample Inventory File**
Here is my suggestion for how to apply this per listener

```
    kafka_broker_custom_listeners:
    ## You can even add additional listeners, make sure name and port are unique
      client_listener:
        name: SECURE_STUFF
        port: 9443
        fips_enabled: true
```

The fips_enabled flag on a specific listener would therefore setup all the necessary SSL, while not necessarily needing to set the `fips_enabled` flag on Kafka
