### ISSUE TITLE
Keytab paths differ in client.properties and server.properties

### ISSUE THREAD

**Issue by Fobhep** [confluentinc/cp-ansible#677]
**For Confluent Enterprise Support customers, we would strongly advise you to open a Support ticket which will be addressed within your Support contract SLA at ```https://support.confluent.io```**

**Describe the issue**
When using upgrade playbooks from 5.5.4 to 6.6.1 - admin-client call for detecting under replicated topics failes due to  a wrong configure keytab path in the /etc/kafka/client.properties file.

**To Reproduce**
Block from inventory for the brokers

```
kafka_broker:
  hosts:
    group0-broker1.hcloud-kafka-lab.test:
      ansible_host: broker1
      broker_id: 1
      kafka_broker_kerberos_keytab_path: ~/kerbldap/keytabs/kafka-broker1.keytab
      kafka_broker_kerberos_principal: kafka/group0-broker1.hcloud-kafka-lab.test@HCLOUD-KAFKA-LAB.TEST
      kafka_broker_custom_properties:
        broker.rack: rack-1
    group0-broker2.hcloud-kafka-lab.test:
      ansible_host: broker2
      broker_id: 2
      kafka_broker_kerberos_keytab_path: ~/kerbldap/keytabs/kafka-broker2.keytab
      kafka_broker_kerberos_principal: kafka/group0-broker2.hcloud-kafka-lab.test@HCLOUD-KAFKA-LAB.TEST
      kafka_broker_custom_properties:
        broker.rack: rack-2
    group0-broker3.hcloud-kafka-lab.test:
      ansible_host: broker3
      broker_id: 3
      kafka_broker_kerberos_keytab_path: ~/kerbldap/keytabs/kafka-broker3.keytab
      kafka_broker_kerberos_principal: kafka/group0-broker3.hcloud-kafka-lab.test@HCLOUD-KAFKA-LAB.TEST
      kafka_broker_custom_properties:
        broker.rack: rack-3
```

block from created server.properties file on broker3
```
listener.name.broker.ssl.truststore.location=/var/ssl/private/kafka_broker.truststore.jks
listener.name.broker.ssl.truststore.password=confluenttruststorepass
listener.name.broker.ssl.keystore.location=/var/ssl/private/kafka_broker.keystore.jks
listener.name.broker.ssl.keystore.password=confluentkeystorestorepass
listener.name.broker.ssl.key.password=confluentkeystorestorepass
listener.name.broker.sasl.enabled.mechanisms=GSSAPI
listener.name.broker.sasl.kerberos.service.name=kafka
listener.name.broker.gssapi.sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required \
  useKeyTab=true \
  storeKey=true \
  keyTab="/etc/security/keytabs/kafka-broker3.keytab" \
  principal="kafka/group0-broker3.hcloud-kafka-lab.test@HCLOUD-KAFKA-LAB.TEST";
```

part of /etc/client.properties file on broker3
```
# Maintained by Ansible
sasl.jaas.config=com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/etc/security/keytabs/kafka_broker.keytab" principal="kafka/group0-broker3.hcloud-kafka-lab.test@HCLOUD-KAFKA-LAB.TEST";
``` 

As you can see the paths in the listener config and the client.properties file differ.

**Expected behaviour**
The keyTab paths should be equivalent

**Environment (please complete the following information):**
 - OS: RHEL 7.4
 - CP-Ansible Branch: 6.6.1
 - Ansible Version 2.9

I guess I might be doing something wrong here?
