### ISSUE TITLE
[confluent.zookeeper : Set Zookeeper Data Dir Ownership] dict object' has no attribute 'properties

### ISSUE THREAD

**Issue by AdamSzendrei** [confluentinc/cp-ansible#706]
I have the following issue on CP-Ansible Branch: [6.2.0-post], I tried CP-Ansible Branch: [6.1.2-post] as well.

```
TASK [confluent.zookeeper : Set Zookeeper Data Dir Ownership] ***************************************************************************************************************************************************************************************************
task path: /vagrant/roles/confluent.zookeeper/tasks/main.yml:118
fatal: [192.168.188.181]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: {{ zookeeper_combined_properties | combine(zookeeper_custom_properties) }}: {{ zookeeper.properties }}: 'dict object' has no attribute 'properties'\n\nThe error appears to be in '/vagrant/roles/confluent.zookeeper/tasks/main.yml': line 118, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Set Zookeeper Data Dir Ownership\n  ^ here\n"
}
```

I'm trying to deploy into a Vagrant environment.

My host.yaml File:
```
---
all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_connection: ssh
    ansible_user: vagrant
    ansible_become: true
    ansible_port: 22
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

zookeeper:
  hosts:
    192.168.188.181:

kafka_broker:
  hosts:
    192.168.188.181:

schema_registry:
  hosts:
    192.168.188.191:

ksql:
  hosts:
    192.168.188.185:

control_center:
  hosts:
    192.168.188.201:
```

My Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.provider 'virtualbox'
  config.ssh.insert_key = false


  etc_hosts = "192.168.188.181\tbro1\tbro1\n" +
              "192.168.188.185\tksql\tksql\n" +
              "192.168.188.191\treg1\treg1\n" +
              "192.168.188.201\tcc1\tcc1\n" +
              "192.168.188.211\ttest1\ttest1"
  config.vm.provision 'shell', inline: "printf '#{etc_hosts}' > /etc/hosts"

  config.vm.define "bro1" do |subconfig|
    subconfig.vm.network "private_network", ip: "192.168.188.181"
    subconfig.vm.hostname = "bro1"
    subconfig.vm.box = "centos/7"
  end

  config.vm.define "ksql" do |subconfig|
    subconfig.vm.network "private_network", ip: "192.168.188.185"
    subconfig.vm.hostname = "ksql"
    subconfig.vm.box = "centos/7"
  end

  config.vm.define "reg1" do |subconfig|
    subconfig.vm.network "private_network", ip: "192.168.188.191"
    subconfig.vm.hostname = "reg1"
    subconfig.vm.box = "centos/7"
  end

  config.vm.define "cc1" do |subconfig|
    subconfig.vm.network "private_network", ip: "192.168.188.201"
    subconfig.vm.hostname = "cc1"
    subconfig.vm.box = "centos/7"
  end

  config.vm.define "test1" do |subconfig|
    subconfig.vm.network "private_network", ip: "192.168.188.211"
    subconfig.vm.hostname = "test1"
    subconfig.vm.box = "centos/7"
  end

  config.vm.define "provisioner" do |subconfig|
    subconfig.vm.network "private_network", ip: "192.168.188.215"
    subconfig.vm.hostname = "provisioner"
    subconfig.vm.box = "centos/8"
    subconfig.vm.provision "shell", inline: "dnf --assumeyes install python3"
    subconfig.vm.provision "shell", inline: "pip3 install --upgrade pip"
    subconfig.vm.provision "shell", privileged:false, inline: "pip3 install --user ansible"
    subconfig.vm.provision "shell", privileged:false, inline: "cp /vagrant/vagrant_insecure_private_key ~/.ssh/id_rsa" 
    subconfig.vm.provision "shell", privileged:false, inline: "chmod 600 ~/.ssh/id_rsa"
    subconfig.vm.provision "shell", privileged:false, inline: "ansible-playbook --become -i /vagrant/hosts.yml /vagrant/all.yml"
  end
  config.vm.box_check_update = false
end

```

Can you please help me to find the issue?

**Comment by domenicbove** [comment]
Usually that error pops up when you do not have hash merging enabled, which gets configured in your ansible.cfg. I see in the provisioner script it runs
```
ansible-playbook --become -i /vagrant/hosts.yml /vagrant/all.yml
```
we keep an ansible.cfg in the root of cp-ansible... so maybe change directories

This is odd though because there is a mash merging check that runs, which should have failed if that was the case.

**Comment by AdamSzendrei** [comment]
Indeed I had to comment out the following section:
```
- name: Confirm Hash Merging Enabled
  assert:
    that: lookup('config', 'DEFAULT_HASH_BEHAVIOUR') == 'merge'
    fail_msg: "Hash Merging must be enabled in ansible.cfg: Confirm current directory is cp-ansible and permissions are set to 755 not 777"
```

because I got this error:

```
    provisioner: TASK [confluent.common : Confirm Hash Merging Enabled] *************************
    provisioner: fatal: [192.168.188.181]: FAILED! => {
    provisioner:     "assertion": "lookup('config', 'DEFAULT_HASH_BEHAVIOUR') == 'merge'",
    provisioner:     "changed": false,
    provisioner:     "evaluated_to": false,
    provisioner:     "msg": "Hash Merging must be enabled in ansible.cfg: Confirm current directory is cp-ansible and permissions are set to 755 not 777"
    provisioner: }
```

Does it mean I have to start ansible-playbook in root directory and I won't have an issue with hashing?

```
[vagrant@provisioner vagrant]$ pwd
/vagrant
[vagrant@provisioner vagrant]$ ls
CODE_OF_CONDUCT.md    Jenkinsfile               VARIABLES.md  control_center.yml  hosts_3006_plain.yml  kafka_connect.yml             roles                tasks                                upgrade_kafka_connect.yml    upgrade_zookeeper.yml
CONTRIBUTING.md       LICENSE.md                Vagrantfile   doc.py              hosts_3006_ssl.yml    kafka_connect_replicator.yml  sample_inventories   upgrade_control_center.yml           upgrade_kafka_rest.yml       vagrant_insecure_private_key
DEVELOPMENT_GUIDE.md  PULL_REQUEST_TEMPLATE.md  all.yml       fetch_logs.yml      hosts_example.yml     kafka_rest.yml                schema_registry.yml  upgrade_kafka_broker.yml             upgrade_ksql.yml             zookeeper.yml
HOW_TO_TEST.md        README.md                 ansible.cfg   hosts.yml           kafka_broker.yml      ksql.yml                      ssl                  upgrade_kafka_broker_log_format.yml  upgrade_schema_registry.yml
[vagrant@provisioner vagrant]$ ansible-playbook --become -i /vagrant/hosts_3006_ssl.yml /vagrant/all.yml --diff
```

**Comment by erikgb** [comment]
@AdamSzendrei You can either change the working directory to pick up the `ansible.cfg` file provided with cp-ansible. But there are also other ways to tell ansible to enable hash merging:
- Set the `ANSIBLE_HASH_BEHAVIOUR` environment variable
- Supply the absolute path to `ansible.cfg` when invoking ansible-playbook.

Hash merging enabled is currently a hard requirement to use cp-ansible. The hash merging feature is deprecated in ansible, and will be removed in ansible-core 2.12. So we are working on removing that requirement in cp-ansible..... But not yet there...

**Comment by AdamSzendrei** [comment]
I set ANSIBLE_CONFIG environment variable of the config file and now it is running. Thank you @erikgb @domenicbove !

```
[vagrant@provisioner /]$ echo $ANSIBLE_CONFIG
/vagrant/ansible.cfg
```

Another error poped up and I'm not sure if it related to the config file issue. If I run the playbooks with --check, I get this error:

`ansible-playbook --become -i /vagrant/hosts_3006_ssl.yml /vagrant/all.yml --diff --check`

```
TASK [confluent.common : Parse Kafka Cluster ID from json query] ************************************************************************************************************************************************************************************************
Thursday 01 July 2021  09:36:25 +0000 (0:00:00.507)       0:01:05.792 ********* 
fatal: [bro1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'json'\n\nThe error appears to be in '/vagrant/roles/confluent.common/tasks/rbac_setup.yml': line 16, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Parse Kafka Cluster ID from json query\n  ^ here\n"}
```

Without --check the playbooks are running fine.

**Comment by domenicbove** [comment]
Hmm, that may be a bug where that task should not run in check mode. Check mode means you probably cant hit the MDS for data

**Comment by erikgb** [comment]
We usually allow reads in check mode, but I do not know MDS.

**Comment by domenicbove** [comment]
@erikgb IDK about polling another system for data though in check mode? I'm guessing the URI module doesn't actually make requests in check mode. i think thats what this is.

**Comment by erikgb** [comment]
I think it would never do that by default. But we can force it, if we know that it is harmless, as we sometimes do when using command/shell modules.

**Comment by domenicbove** [comment]
Ya so if these are the tasks:
```
- name: Get Kafka Cluster ID from Embedded Rest Proxy
  uri:
    url: "{{mds_http_protocol}}://{{ hostvars[groups['kafka_broker'][0]] | resolve_hostname }}:{{mds_port}}/kafka/v3/clusters"
    method: GET
    validate_certs: false
    body_format: json
    return_content: true
    status_code: 200
    url_username: "{{mds_super_user}}"
    url_password: "{{mds_super_user_password}}"
    force_basic_auth: true
  register: cluster_id_query
  when: cluster_id_source | default('erp') == 'erp'

- name: Parse Kafka Cluster ID from json query
  set_fact:
    kafka_cluster_id: "{{ cluster_id_query.json.data[0].cluster_id }}"
  when: cluster_id_source | default('erp') == 'erp'
```

Then the uri module doesnt return data in check mode, and then this set fact should not run
