### ISSUE TITLE
Install community edition?

### ISSUE THREAD

**Issue by mickaelgervais** [confluentinc/cp-ansible#85]
Is it possible to use your playbook to install component which are only in the community edition?

I'd like to use the broker, schema registry and rest proxy components only. 

Thanks

**Comment by cricket007** [comment]
Yes. You can exclude using the Control Center playbook and remove the monitoring interceptors from the respective components.

**Comment by cricket007** [comment]
You could also try setting these variables

```yaml
confluent:
  package_name: confluent-platform-oss-2.11
  support:
    customer_id: anonymous
    metrics_enabled: false
```

Which are defined here - https://github.com/confluentinc/cp-ansible/blob/5.1.x/roles/confluent.common/defaults/main.yml

**Comment by michalklempa** [comment]
In 5.1.x branch and 5.x version on CentOS, the package name is confluent-community-2.11:
```
        # confluentinc
        security_mode: plaintext
        confluent_version: "5.0.1"

        confluent:
          package_name: confluent-community-2.11
          support:
            metrics_enabled: false
```
