### ISSUE TITLE
confluent.ssl playbook updates only broker's jks ignoring all others.

### ISSUE THREAD

**Issue by ay-b** [confluentinc/cp-ansible#879]
We're playing with Kafka on-premise and using LetsEncrypt to generate certificates.
All variables for custom certificates were set up and initial deployment worked as intended.
Recently LE-cert has expired and we need to update jks-bundles. 
So I've copied LE cert-files and used `confluent.ssl` playbook to generate new bundles. 
However, this playbook did update only for the broker jks-bundle, ignoring other components and even zookeeper. Running `minimal` and `connect` deployments playbooks fixed the situation, but is extremely inconvenient due to the prolonged service outage.

- Generate LE wildcard certs
- Set all variables for custom certs in role
- Deploy Kafka Minimal+Connect
- Wait for certs to expire
- Run `confluent_ssl` playbook

**Expected behaviour**
Kafka brokers, schema and connect jks-bundles being regenerated, services restarted and everything is up again

**Inventory File**
```yaml
---
all:
  vars:
    ansible_connection: ssh
    ansible_user: superuser
    ansible_port: 32329
    ansible_become: true
    ansible_python_interpreter: /usr/bin/python3
    sasl_protocol: plain
    zookeeper_sasl_protocol: digest
    ssl_enabled: true
    ssl_custom_certs: true
    ssl_key_filepath: "/etc/letsencrypt/live/domain.name/privkey.pem"
    regenerate_keystore_and_truststore: true
    jmxexporter_enabled: true
    confluent_server_enabled: false
    admin_secret: secret
    client_secret: secret
    schema_registry_secret: secret
    kafka_connect_secret: secret
    kafka_rest_secret: secret
    ksql_secret: secret
    control_center_secret: secret
    kafka_connect_replicator_secret: secret
    kafka_broker_secret: secret
    mds_super_user_password: secret
    schema_registry_ldap_password: secret
    kafka_connect_ldap_password: secret
    kafka_rest_ldap_password: secret
    control_center_ldap_password: secret
    kafka_connect_replicator_ldap_password: secret
    _sasl_scram_users: "{
      'admin': {
        'principal': 'admin',
        'password': '{{admin_secret}}'
      },
      'client': {
        'principal': 'client',
        'password': '{{client_secret}}'
      }{% if 'schema_registry' in groups %},
      'schema_registry': {
        'principal': 'schema_registry',
        'password': '{{schema_registry_secret}}'
      }{% endif %}{% if 'kafka_connect' in groups %},
      'kafka_connect': {
        'principal': 'kafka_connect',
        'password': '{{kafka_connect_secret}}'
      }{% endif %}{% if 'kafka_rest' in groups %},
      'kafka_rest': {
        'principal': 'kafka_rest',
        'password': '{{kafka_rest_secret}}'
      }{% endif %}{% if 'ksql' in groups %},
      'ksql': {
        'principal': 'ksql',
        'password': '{{ksql_secret}}'
      }{% endif %}{% if 'control_center' in groups %},
      'control_center': {
        'principal': 'control_center',
        'password': '{{control_center_secret}}'
      }{% endif %}{% if 'kafka_connect_replicator' in groups %},
      'kafka_connect_replicator': {
        'principal': 'kafka_connect_replicator',
        'password': '{{kafka_connect_replicator_secret}}'
      }{% endif %}
    }"
    sasl_scram_users: {}
    _sasl_scram256_users: "{
      'admin': {
        'principal': 'admin',
        'password': '{{admin_secret}}'
      },
      'client': {
        'principal': 'client',
        'password': '{{client_secret}}'
      }{% if 'schema_registry' in groups %},
      'schema_registry': {
        'principal': 'schema_registry',
        'password': '{{schema_registry_secret}}'
      }{% endif %}{% if 'kafka_connect' in groups %},
      'kafka_connect': {
        'principal': 'kafka_connect',
        'password': '{{kafka_connect_secret}}'
      }{% endif %}{% if 'kafka_rest' in groups %},
      'kafka_rest': {
        'principal': 'kafka_rest',
        'password': '{{kafka_rest_secret}}'
      }{% endif %}{% if 'ksql' in groups %},
      'ksql': {
        'principal': 'ksql',
        'password': '{{ksql_secret}}'
      }{% endif %}{% if 'control_center' in groups %},
      'control_center': {
        'principal': 'control_center',
        'password': '{{control_center_secret}}'
      }{% endif %}{% if 'kafka_connect_replicator' in groups %},
      'kafka_connect_replicator': {
        'principal': 'kafka_connect_replicator',
        'password': '{{kafka_connect_replicator_secret}}'
      }{% endif %}
    }"
    sasl_scram256_users: {}
    _sasl_plain_users: "{
      'admin': {
        'principal': 'admin',
        'password': '{{admin_secret}}'
      },
      'client': {
        'principal': 'client',
        'password': '{{client_secret}}'
      }{% if 'schema_registry' in groups %},
      'schema_registry': {
        'principal': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_key}}{% else %}schema_registry{% endif %}',
        'password': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_secret}}{% else %}{{schema_registry_secret}}{% endif %}'
      }{% endif %}{% if 'kafka_connect' in groups %},
      'kafka_connect': {
        'principal': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_key}}{% else %}kafka_connect{% endif %}',
        'password': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_secret}}{% else %}{{kafka_connect_secret}}{% endif %}'
      }{% endif %}{% if 'kafka_rest' in groups %},
      'kafka_rest': {
        'principal': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_key}}{% else %}kafka_rest{% endif %}',
        'password': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_secret}}{% else %}{{kafka_rest_secret}}{% endif %}'
      }{% endif %}{% if 'ksql' in groups %},
      'ksql': {
        'principal': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_key}}{% else %}ksql{% endif %}',
        'password': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_secret}}{% else %}{{ksql_secret}}{% endif %}'
      }{% endif %}{% if 'control_center' in groups %},
      'control_center': {
        'principal': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_key}}{% else %}control_center{% endif %}',
        'password': '{% if ccloud_kafka_enabled|bool %}{{ccloud_kafka_secret}}{% else %}{{control_center_secret}}{% endif %}'
      }{% endif %}{% if 'kafka_connect_replicator' in groups %},
      'kafka_connect_replicator': {
        'principal': 'kafka_connect_replicator',
        'password': '{{kafka_connect_replicator_secret}}'
      }{% endif %}
    }"
    sasl_plain_users: {}
    zookeeper_digest_users:
      admin:
        principal: admin
        password: "{{admin_secret}}"
      kafka_broker:
        principal: kafka_broker
        password: "{{kafka_broker_secret}}"
    kafka_broker_rest_proxy_basic_users:
      admin:
        principal: admin
        password: "{{admin_secret}}"
        roles: admin
    _schema_registry_basic_users: "{
      'admin': {
        'principal': '{% if ccloud_schema_registry_enabled|bool %}{{ccloud_schema_registry_key}}{% else %}admin{% endif %}',
        'password': '{% if ccloud_schema_registry_enabled|bool %}{{ccloud_schema_registry_secret}}{% else %}{{admin_secret}}{% endif %}',
        'roles': 'admin'
      }
    }"
    kafka_connect_basic_users:
      admin:
        principal: admin
        password: "{{admin_secret}}"
    ksql_basic_users:
      admin:
        principal: admin
        password: "{{admin_secret}}"
        roles: admin
    kafka_rest_basic_users:
      admin:
        principal: admin
        password: "{{admin_secret}}"
        roles: admin
    control_center_basic_users:
      admin:
        principal: admin
        password: "{{admin_secret}}"
        roles: admin
zookeeper:
  hosts:
    kfk-1.domain.name:
    kfk-2.domain.name:
    kfk-3.domain.name:
kafka_broker:
  confluent.balancer.enable: "true"
  hosts:
    kfk-1.domain.name:
    kfk-2.domain.name:
    kfk-3.domain.name:
schema_registry:
  hosts:
    kfk-1.domain.name:
kafka_rest:
  hosts:
    kfk-1.domain.name:
ksql:
  hosts:
    kfk-2.domain.name:
kafka_connect:
  hosts:
    kfk-2.domain.name:
control_center:
  hosts:
    kfk-2.domain.name:
```

**Logs**
Nothing failed, just incomplete run. Probably, problem is with the facts collection regarding packages deployed and needed to be updated.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - CP-Ansible Branch: 6.9.2-post
 - Ansible Version 2.9.2

**Additional context**
just need help with fixing that behavior.
