### ISSUE TITLE
Upgrading platform via playbook

### ISSUE THREAD

**Issue by baunz** [confluentinc/cp-ansible#90]
Hi,

what would be the best way to upgrade an existing version (installed with the playbooks) to a newer version, say, 5.1.0 to 5.1.2?

Would it be sufficient to include an  ````upgrade: yes```` in the respective -common task files, e.g. for debian
in roles/cp-ansible/roles/confluent.common/tasks/debian.yml
```
- name: Install the Confluent Platform
  apt:
    name: "{{confluent.package_name}}"
    update_cache: yes
    upgrade: yes
````

Is this something worth externalizing?

Thanks!
