### ISSUE TITLE
"Create Log Directory" task is failed in V7.0.1's Ansible Installation

### ISSUE THREAD

**Issue by hata0727** [confluentinc/cp-ansible#992]
**For Confluent Enterprise Support customers, we would strongly advise you to open a Support ticket which will be addressed within your Support contract SLA at ```https://support.confluent.io```**

**Describe the issue**
In trying to execute Ansible Playbooks in V7.0.1 (https://docs.confluent.io/ansible/current/overview.html), following error is always seen, which is preventing from our installation.

```
TASK [zookeeper : Create Log Directory] ****************************************
task path: /work2/cp-ansible/playbooks/roles/zookeeper/tasks/main.yml:177
fatal: [172.16.253.74]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: {{zookeeper.log_path}}: 'dict object' has no attribute 'log_path'\n\nThe error appears to be in '/work2/cp-ansible/playbooks/roles/zookeeper/tasks/main.yml': line 177, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create Log Directory\n  ^ here\n"
}
fatal: [172.16.240.16]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: {{zookeeper.log_path}}: 'dict object' has no attribute 'log_path'\n\nThe error appears to be in '/work2/cp-ansible/playbooks/roles/zookeeper/tasks/main.yml': line 177, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create Log Directory\n  ^ here\n"
}
fatal: [172.16.251.72]: FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: {{zookeeper.log_path}}: 'dict object' has no attribute 'log_path'\n\nThe error appears to be in '/work2/cp-ansible/playbooks/roles/zookeeper/tasks/main.yml': line 177, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Create Log Directory\n  ^ here\n"
}

PLAY RECAP *********************************************************************
172.16.240.16              : ok=28   changed=0    unreachable=0    failed=1    skipped=23   rescued=0    ignored=0   
172.16.251.72              : ok=28   changed=0    unreachable=0    failed=1    skipped=23   rescued=0    ignored=0   
172.16.253.74              : ok=28   changed=0    unreachable=0    failed=1    skipped=23   rescued=0    ignored=0  
```

**To Reproduce**
Execute following command

`# ansible-playbook -i hosts.yml all.yml --tags=zookeeper`

, where hosts.yaml is modified as as following and all.yaml is default.

```
---
all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_password: rhvm@123
    ansible_become: true
    installation_method: archive
    confluent_archive_file_source: /root/confluent-7.0.1.tar.gz
    confluent_archive_file_remote: false
    jmxexporter_enabled: true
    jolokia_enabled: true
    confluent_license: xyz

    zookeeper_custom_properties:
      initLimit: 6
      syncLimit: 3
      confluent.license: "{{ confluent_license }}"
    kafka_broker_custom_properties:
      num.io.threads: 15
      confluent.license: "{{ confluent_license }}"
    schema_registry_custom_properties:
      confluent.license: "{{ confluent_license }}"
    kafka_connect_custom_properties:
      confluent.license: "{{ confluent_license }}"
    control_center_custom_properties:
      confluent.license: "{{ confluent_license }}"
    kafka_rest_custom_properties:
      confluent.license: "{{ confluent_license }}"
    ksql_custom_properties:
      confluent.license: "{{ confluent_license }}"

zookeeper:
  hosts:
    172.16.253.74:
    172.16.240.16:
    172.16.251.72:

kafka_broker:
  hosts:
    172.16.253.74:
      broker_id: 1
    172.16.240.16:
      broker_id: 2
    172.16.251.72:
      broker_id: 3

schema_registry:
  hosts:
    172.16.253.74:

kafka_rest:
  hosts:
    172.16.253.74:

ksql:
  hosts:
    172.16.253.74:

kafka_connect:
  hosts:
    172.16.253.74:

control_center:
  hosts:
    172.16.253.74:
```

**Expected behaviour**
This task mush be completed without any errors.

**Inventory File**
Please see the above attached.

**Logs**
Please see the above attached.

**Environment (please complete the following information):**
 - Red Hat Enterprise Linux release 8.5 (Ootpa)
 - CP-Ansible Branch: [7.0.1]
 - Ansible Version [core 2.11.9]

**Additional context**
N/A

**Comment by utkarsh5474** [comment]
Hi, that shouldn't happen. all.yml calls zookeeper.yml which imports all the variables [here](https://github.com/confluentinc/cp-ansible/blob/7.0.1-post/playbooks/zookeeper.yml#L8). zookeeper.log_path is defined [here](https://github.com/confluentinc/cp-ansible/blob/7.0.1-post/roles/variables/defaults/main.yml#L272)'
Having said that, our docs [here](https://docs.confluent.io/ansible/current/ansible-install.html) suggest using confluent.platform.all and not all.yml 
Please use that - `ansible-playbook -i hosts.yml confluent.platform.all --tags=zookeeper`

**Comment by utkarsh5474** [comment]
Suggested and the correct way to download cp-ansible 7.0.1 with ansible version 2.11 is using ansible galaxy - https://docs.confluent.io/ansible/current/ansible-download.html#download-playbooks-using-ansible-galaxy
Reason being from 7.0.1 onwards, cp-ansible is bundled as a collection. If you use git clone, things won't work the suggested way. 
If for some reason you just can't use galaxy install, set the env var `ANSIBLE_COLLECTIONS_PATH: /path/to/ansible_collection` before running any playbooks and run them the suggested way on the docs.

**Comment by hata0727** [comment]
I have also tried the above steps before opening this issue, but I can't find out confluent.platform.all. As you see below snippets, I can just find out "all.yml", not "confluent.platform.all".

```
[root@vm2 work3]# ansible-galaxy collection install \
>   git+https://github.com/confluentinc/cp-ansible.git
Cloning into '/root/.ansible/tmp/ansible-local-5906716ta1dmu2/tmpaxs5wp5v/cp-ansibled87jyc27'...
remote: Enumerating objects: 43671, done.
remote: Counting objects: 100% (2841/2841), done.
remote: Compressing objects: 100% (1340/1340), done.
remote: Total 43671 (delta 1666), reused 2477 (delta 1429), pack-reused 40830
Receiving objects: 100% (43671/43671), 7.53 MiB | 12.57 MiB/s, done.
Resolving deltas: 100% (28169/28169), done.
Your branch is up to date with 'origin/7.0.1-post'.
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'confluent.platform:7.0.1' to '/root/.ansible/collections/ansible_collections/confluent/platform'
Created collection for confluent.platform:7.0.1 at /root/.ansible/collections/ansible_collections/confluent/platform
confluent.platform:7.0.1 was installed successfully

[root@vm2 playbooks]# ls -ltr /root/.ansible/collections/ansible_collections/confluent/platform/playbooks
合計 40
-rw-r--r--. 1 root root 3464  3月 29 21:38 fetch_logs.yml
-rw-r--r--. 1 root root 1380  3月 29 21:38 control_center.yml
-rw-r--r--. 1 root root 1507  3月 29 21:38 all.yml
-rw-r--r--. 1 root root 1320  3月 29 21:38 kafka_rest.yml
-rw-r--r--. 1 root root 1530  3月 29 21:38 kafka_connect_replicator.yml
-rw-r--r--. 1 root root 1365  3月 29 21:38 kafka_connect.yml
-rw-r--r--. 1 root root 2008  3月 29 21:38 kafka_broker.yml
drwxr-xr-x. 2 root root   60  3月 29 21:38 tasks
-rw-r--r--. 1 root root  535  3月 29 21:38 schema_registry.yml
-rw-r--r--. 1 root root 1205  3月 29 21:38 ksql.yml
-rw-r--r--. 1 root root 1916  3月 29 21:38 zookeeper.yml
```

**Comment by utkarsh5474** [comment]
`confluent.platform.all` is how the all.yml will be resolved when cp-ansible is bundled as a collection. It's the same thing.
Run the commands as mentioned in doc and report back the command and logs if you still hit an issue.

**Comment by hata0727** [comment]
Thank you so much for your comments. After setting following environment variable, then I executed `ansible-playbook -i hosts.yml all.yml --tags=zookeeper` command and I am seeing following new error;

```
[root@vm2 playbooks]# ansible-playbook -i hosts.yml all.yml --tags=zookeeper
ERROR! couldn't resolve module/action 'sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/.ansible/collections/ansible_collections/confluent/platform/playbooks/roles/kafka_broker/tasks/main.yml': line 354, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Tune virtual memory settings
  ^ here
```

Here, my hosts.yml is as following;

```
---
all:
  vars:
    ansible_connection: ssh
    ansible_user: root
    ansible_password: rhvm@123
    ansible_become: true
    installation_method: archive
    confluent_archive_file_source: /root/confluent-7.0.1.tar.gz
    confluent_archive_file_remote: false
    jmxexporter_enabled: true
    jolokia_enabled: true
    confluent_license: xyz

    zookeeper_custom_properties:
      initLimit: 6
      syncLimit: 3
      confluent.license: "{{ confluent_license }}"
    kafka_broker_custom_properties:
      num.io.threads: 15
      confluent.license: "{{ confluent_license }}"
    schema_registry_custom_properties:
      confluent.license: "{{ confluent_license }}"
    kafka_connect_custom_properties:
      confluent.license: "{{ confluent_license }}"
    control_center_custom_properties:
      confluent.license: "{{ confluent_license }}"
    kafka_rest_custom_properties:
      confluent.license: "{{ confluent_license }}"
    ksql_custom_properties:
      confluent.license: "{{ confluent_license }}"

zookeeper:
  hosts:
    vm2:
    vm3:
    vm4:

kafka_broker:
  hosts:
    vm2:
      broker_id: 1
    vm3:
      broker_id: 2
    vm4:
      broker_id: 3

schema_registry:
  hosts:
    vm2:

kafka_rest:
  hosts:
    vm2:

ksql:
  hosts:
    vm2:

kafka_connect:
  hosts:
    vm2:

control_center:
  hosts:
    vm2:
```
