### ISSUE TITLE
Parameters to install the community edition of 5.5.x

### ISSUE THREAD

**Issue by VolodymyrLenyk** [confluentinc/cp-ansible#994]
Hi,
I want to use Ansible to install the components from the community edition (zookeeper, broker, rest-proxy, schema registry).
Can you help with the parameters that I must pass to install the 5.5.x community version: https://packages.confluent.io/archive/5.5/?

In the 5.1.x version it was something like this:
```
confluent:
  package_name: confluent-platform-oss-2.11
  support:
    customer_id: anonymous
    metrics_enabled: false
```
